database:
  image: mysql:5.7
  ports:
    - "3307:3306"
  env_file:
    - ./conf/env/MYSQL.env
  mem_limit: 500M

smtp:
  image: schickling/mailcatcher
  ports:
    - "1007:1080"
  mem_limit: 256M

formation17:
 container_name: formation-shop-ps17
 dockerfile: ./conf/docker/Dockerfile
 build: .
 ports:
   - "8080:8080"
 links:
   - smtp
   - database
 env_file:
   - ./conf/env/PRESTASHOP.env
 volumes:
   - ./web17:/var/www/html
   - ./src/formation:/var/www/html/modules/formation
 mem_limit: 500M
