<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrbnau9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrbnau9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKrbnau9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKrbnau9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKrbnau9\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Krbnau9',
    'container.build_id' => 'e5a848c2',
    'container.build_time' => 1539355711,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrbnau9');
