<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVdzxrtn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVdzxrtn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVdzxrtn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVdzxrtn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVdzxrtn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vdzxrtn',
    'container.build_id' => '4de98440',
    'container.build_time' => 1539333307,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVdzxrtn');
