<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYtnjui8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYtnjui8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYtnjui8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYtnjui8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYtnjui8\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ytnjui8',
    'container.build_id' => 'f5a2fc0d',
    'container.build_time' => 1538834444,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYtnjui8');
