<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwgwabf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwgwabf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEwgwabf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEwgwabf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEwgwabf\appProdProjectContainer(array(
    'container.build_hash' => 'Ewgwabf',
    'container.build_id' => 'c10527f4',
    'container.build_time' => 1539114724,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwgwabf');
